include:
  - local: '.gitlab-ci-template.yml'
  - project: clops/gitlab-ci-pop-analysis
    ref: master
    file: pop_analysis.yaml
  - project: releng/common-gitlab-ci
    ref: master
    file: sbom-generate.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_versioning.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_common.yml

# List of job stages in their order of execution.
stages:
  - build
  - contract_test
  - coverage_report
  - versioning
#  - Check_dist
#  - changelog
  - analysis
  - sbom
  - notification


variables:
  BUILD_TOOL: npm
  GIT_DEPTH: 10
  BD_PRODUCT_GROUP: PolarisNG Projects Group
  BD_VERSION_PHASE: DEVELOPMENT

##### MERGE REQUEST PIPELINE #####

build_unit_test_job:
  extends:
    - .build_unit_tests
  stage: build

contract_test_job:
  extends:
    - .contract_tests
  stage: build

code_coverage_job:
  stage: coverage_report
  extends:
    -  .code_coverage

#check_dist_job:
#  extends:
#    - .check_dist
#  stage: Check_dist

##### MASTER COMMIT PIPELINE #####
versioning_job:
  extends:
    - .version # Triggers git semver, job details will be fetched from altair build common repository
    - .retry
  stage: versioning
  tags:
    - linux64-docker
  dependencies:
    - build_job

.export_sbom_variables:
  before_script:
    - export EXT_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    - export ARTIFACTORY_UPLOAD_REPO=1
    - export SBOM_ART_TOKEN_VAULT_PATH=sbom/integrations/github-actions
    - export PRODUCT=Integrations
    - export GENERATE_CONFIGURATION_FILE=1
    - export GENERATION_OPTIONS="--entry integrations/synopsys-action/synopsys-action-ci-cd:synopsys-action-ci-cd-$EXT_VERSION"
    - export PRODUCT_ADDON_SBOM_OPTIONS="--output-zipfile synopsys-ci-cd-actions-$EXT_VERSION-.zip"

generate_sbom:
  extends:
    - .export_sbom_variables
    - .run_sbom_generation
  stage: sbom
  only:
    refs:
      - main


pop_polaris:
  image: gcr.io/snps-polaris-ops-prod/ember_cli:3.28.5-node_16.14

polaris_bridge:
  stage: analysis
  extends: .polaris_bridge

pop_blackduck:
  image: gcr.io/snps-polaris-ops-prod/altair-maven-build-jdk11:1.0.43
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
  dependencies:
    - versioning_job
  extends:
    - .new_pop_blackduck
  before_script:
    - |
      apt -y update
      apt -y install make python3 python3-pip
      pip install blackduck requests
      export RELEASE_VERSION=$(cat version.txt)

#changelog_job:
#  extends:
#    - .changelog
#    - .only
#  stage: changelog
