include:
  - local: '.gitlab-ci-template.yml'
  - project: clops/gitlab-ci-pop-analysis
    ref: master
    file: pop_analysis.yaml
  - project: releng/common-gitlab-ci
    ref: master
    file: sbom-generate.yml

# List of job stages in their order of execution
stages:
  - build
  - contract_test
  - coverage_report
  - versioning
  - sbom
#  - Check_dist
#  - changelog
  - analysis
  - notification


variables:
  BUILD_TOOL: npm
  GIT_DEPTH: 10

##### MERGE REQUEST PIPELINE #####

build_unit_test_job:
  extends:
    - .build_unit_tests
  stage: build

contract_test_job:
  extends:
    - .contract_tests
  stage: build

code_coverage_job:
  stage: coverage_report
  extends:
    -  .code_coverage

#check_dist_job:
#  extends:
#    - .check_dist
#  stage: Check_dist

##### MASTER COMMIT PIPELINE #####
versioning_job:
  extends:
    - .version
    - .only
  stage: versioning


generate_sbom:
  extends:
    - .run_sbom_generation
  stage: sbom
  variables:
    SBOM_ART_TOKEN_VAULT_PATH: sbom/integrations/github-actions
    PRODUCT: synopsys-action-ci-cd
    GENERATE_CONFIGURATION_FILE: 1
    GENERATION_OPTIONS: "--entry Bridge@@Adapters:synopsys-action-ci-cd --provide-zip --output-zipfile Synopsys-CICD-actions.zip"
  only:
    refs:
      - main

polaris_bridge:
  stage: analysis
  extends: .polaris_bridge

pop_blackduck:
  stage: analysis
  extends: .pop_blackduck_analysis



#changelog_job:
#  extends:
#    - .changelog
#    - .only
#  stage: changelog
