# This is a basic workflow to help you get started with Actions

name: CI-Blackduck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "SIGINT-252-GitHub_Action_download_and_keep_bridge_in_github_action_space" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
   runs-on: macos-latest
#    runs-on: [self-hosted, Windows, kiran]
#    runs-on: [self-hosted, Linux, kishor-linux]

   env:
#      BRIDGE_blackduck_url: ${{ secrets.BLACKDUCK_URL }}
#      BRIDGE_blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN_NEW }}
#      BRIDGE_blackduck_install_directory: "/Users/kishori/synopsys-bridge"
      MAC_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/blackduck-hub/0.1.22/blackduck_hub-0.1.22-macosx.zip"
      LINUX_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/blackduck-hub/0.1.22/blackduck_hub-0.1.22-linux64.zip"
      WINDOWS_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/blackduck-hub/0.1.22/blackduck_hub-0.1.22-win64.zip"

    # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


#      - name: Synopsys-action for Windows
#        if: ${{ runner.os == 'Windows' }}
#        run: |
#          Invoke-WebRequest -Uri ${{ env.WINDOWS_BRIDGE_URL }} -OutFile bridge.zip
#          tar -xf bridge.zip
#          .\bridge.exe --stage blackduck
#        shell: powershell
#
#      - name: Synopsys-action for MAC
#        if: ${{  runner.os == 'macOS'  }}
#        run: |
#          var="$(which unzip)"
#          if [[ $var =~ "not found" ]]; then
#            brew install unzip
#          fi
#          curl -o bridge.zip -L $MAC_BRIDGE_URL
#          unzip bridge.zip
#          ./bridge --stage blackduck
#        shell: bash
#
#      - name: Synopsys-action for Linux
#        if: ${{  runner.os == 'Linux'  }}
#        run: |
#          var="$(which unzip)"
#          if [[ $var =~ "not found" ]]; then
#            sudo apt-get install unzip
#          fi
#          curl -o bridge.zip -L $LINUX_BRIDGE_URL
#          unzip bridge.zip
#          ./bridge --stage blackduck
#        shell: bash
#      - name: create required directory
#        sudo mkdir /Users/kishori/synopsys-bridge

      - name: Use synopsys unified-action - blackduck-detect
       # Use the action defined in this repository
        uses: ./
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN_NEW }}
          blackduck_scan_full: true
          blackduck_install_directory: /Users/kishori/synopsys-bridge
          blackduck_scan_failure_severities: "[\"BLOCKER\", \"CRITICAL\", \"TRIVIAL\"]"
          configure_from_repo: true
